In [3]:
!pip install pandas mplsoccer pandas-summary psycopg2-binary

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: mplsoccer in /opt/conda/lib/python3.11/site-packages (1.4.0)
Requirement already satisfied: pandas-summary in /opt/conda/lib/python3.11/site-packages (0.2.0)
Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.11/site-packages (2.9.10)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: matplotlib>=3.6 in /opt/conda/lib/python3.11/site-packages (from mplsoccer) (3.10.0)
Requirement already satisfied: pillow in /opt/conda/lib/python3.11/site-packages (from mplsoccer) (11.0.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from mplsoccer) (2.31.0)
Requirement already satisfied: scipy in /opt/conda/lib/python3.11/site-packages (from mplsoccer) (1.14.1)
Requirement already satisfied: seaborn in /opt/conda/lib/python3.11/site-packages (from mplsoccer) (0.13.2)
Requirement already satisfied: datatile in /opt/conda/lib/python3.11/site-packages (from pandas-summary) (1.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.6->mplsoccer) (3.2.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: traceml<1.1 in /opt/conda/lib/python3.11/site-packages (from datatile->pandas-summary) (1.0.8)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->mplsoccer) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->mplsoccer) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->mplsoccer) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->mplsoccer) (2023.7.22)

In [4]:
import os
import pandas as pd
import numpy as np


# now dump the data to the pg database
import psycopg2
from psycopg2 import sql
from sqlalchemy import create_engine

In [11]:
def get_rival_name(file_name):
    """
    Get the name of the rival from the file name
    'Albion 25-5-2024.csv'     -> albion
    """
    return file_name.split(' ')[0].lower()

def rename_columns(df):
    """
    Rename the columns of the dataframe
    rename columns, because right now those look like this
    "Player Id", " Player Display Name", " Time", " Elapsed Time (s)", " Lat", " Lon", "  Speed km/h", " Instantaneous Acceleration Impulse", " Heart Rate (bpm)"
    and we want them to look like this
    player_id, player_display_name, "time", elapsed_time, lat, lon, speed, instantaneous_acceleration, heart_rate
    """
    df.columns = ['player_id', 'player_display_name', 'time', 'elapsed_time', 'lat', 'lon', 'speed', 'instantaneous_acceleration', 'heart_rate']
    
    return df
  

from sqlalchemy import text

def process_rival_data(file_name, engine):

    print(f"Cargando datos... {file_name}")

    current_rival = get_rival_name(file_name)
    file = 'partidos/' + file_name
    # file = 'work/cargar_datos_base/partidos/' + file_name
    column_names = [
        "Player Id", "Player Display Name", "Time", "Elapsed Time (s)",
        "Lat", "Lon", "Speed km/h", "Instantaneous Acceleration Impulse", "Heart Rate (bpm)", ""
    ]

    datos_csv = pd.read_csv(file, delimiter=',', skiprows=1, names=column_names, encoding='latin1')
    datos_csv = datos_csv.iloc[:, :-1]  # remove the last column, because the csv file has an extra comma at the end
    datos_csv = rename_columns(datos_csv)  # rename the columns to something more db friendly
    
    # check that none of the column names have a \n in them, and if they do, remove it
    datos_csv.columns = datos_csv.columns.str.replace('\n', '')
    datos_csv.columns = datos_csv.columns.str.replace(' ', '_')
    datos_csv.columns = datos_csv.columns.str.lower()
    datos_csv.columns = datos_csv.columns.str.strip()
    datos_csv.columns = datos_csv.columns.str.replace('(', '')
    datos_csv.columns = datos_csv.columns.str.replace(')', '')
    datos_csv.columns = datos_csv.columns.str.replace('/', '_')
    

    with engine.connect() as conn, conn.begin():
        query = text(f"SELECT * FROM information_schema.tables WHERE table_name = '{current_rival}'")
        table_exists = conn.execute(query).fetchone()
        # check if the table already exists, and if it does, we should check also if it has a \n in the column names
        # if it does, we should remove it, so we can insert clean data wth the same column names, but without the \n
        
        has_newline = False
        if table_exists:
            query = text(f"SELECT column_name FROM information_schema.columns WHERE table_name = '{current_rival}'")
            column_names = conn.execute(query).fetchall()
            for column_name in column_names:
                if '\n' in column_name[0]:
                    has_newline = True
                    break
        
        print(f"Table {current_rival} has new line in column names: {has_newline}")
        
        if table_exists and not has_newline:
            print(f"Table {current_rival} already exists")
        else:
            print(f"Table {current_rival} does not exist, or was wrongly created")
            datos_csv.to_sql(current_rival, conn, if_exists='replace', index=False)

    try:
        query = f"SELECT * FROM {current_rival} LIMIT 5"
        df = pd.read_sql(query, engine)
        display(df)
    except Exception as e:
        print(e)
        print("Error al leer la tabla")

# # Example usage:
engine = create_engine('postgresql://nacional:nacional@localhost:5432/nacional')
# file_name = 'Defensor 06-07-2024.csv'
# process_rival_data(file_name, engine)

In [12]:
# now run the function for all the files in the directory
for file_name in os.listdir('partidos'):
# for file_name in os.listdir('work/cargar_datos_base/partidos'):
    if file_name.endswith('.csv'):
        process_rival_data(file_name, engine)

Cargando datos... DeportivoMaldonado 22-6-2024.csv
Table deportivomaldonado has new line in column names: False
Table deportivomaldonado already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,88,Jhonatan Dalmas,10:59:18.40,0.100008,-34.795196,-56.147506,4.930004,0.000000,0
1,88,Jhonatan Dalmas,10:59:18.50,0.200007,-34.795197,-56.147508,5.120004,1.900002,0
2,88,Jhonatan Dalmas,10:59:18.60,0.300007,-34.795197,-56.147509,5.180004,0.600000,0
3,88,Jhonatan Dalmas,10:59:18.70,0.400006,-34.795198,-56.147510,5.320004,1.400001,0
4,88,Jhonatan Dalmas,10:59:18.80,0.500005,-34.795199,-56.147513,5.950005,6.300005,0

Cargando datos... Albion 25-5-2024.csv
Table albion has new line in column names: False
Table albion already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,09:03:56.02,0.019998,-34.795304,-56.147873,1.13889,0.750001,None
1,68,Del Pino Esquivo,09:03:56.03,0.029998,-34.795304,-56.147873,1.13889,0.750001,None
2,68,Del Pino Esquivo,09:03:56.04,0.039998,-34.795304,-56.147873,1.13889,0.750001,None
3,68,Del Pino Esquivo,09:03:56.05,0.049998,-34.795304,-56.147873,1.13889,0.750001,None
4,68,Del Pino Esquivo,09:03:56.06,0.059998,-34.795304,-56.147873,1.13889,0.750001,None

Cargando datos... Defensor 06-07-2024.csv
Table defensor has new line in column names: False
Table defensor already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,09:59:38.50,0.099999,-34.795161,-56.147495,4.820004,9.300007,0
1,68,Del Pino Esquivo,09:59:38.60,0.199998,-34.795161,-56.147495,4.290003,5.300004,0
2,68,Del Pino Esquivo,09:59:38.70,0.299998,-34.795162,-56.147496,4.920004,6.300005,0
3,68,Del Pino Esquivo,09:59:38.80,0.399997,-34.795163,-56.147497,5.190004,2.700002,0
4,68,Del Pino Esquivo,09:59:38.90,0.499997,-34.795164,-56.147498,5.370004,1.800001,0

Cargando datos... Progreso 05-4-2024.csv
Table progreso has new line in column names: False
Table progreso already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,08:51:48.40,0.099999,-34.841747,-56.294339,0.0,0.0,0
1,68,Del Pino Esquivo,08:51:48.50,0.199998,-34.841747,-56.294339,0.0,0.0,0
2,68,Del Pino Esquivo,08:51:48.60,0.299998,-34.841747,-56.294339,0.0,0.0,0
3,68,Del Pino Esquivo,08:51:48.70,0.399997,-34.841747,-56.294339,0.0,0.0,0
4,68,Del Pino Esquivo,08:51:48.80,0.499997,-34.841747,-56.294339,0.0,0.0,0

Cargando datos... CAP 17-5-2024.csv
Table cap has new line in column names: False
Table cap already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,82,Calione Fuentes,12:57:16.42,57436.42,-17.448955,-28.076782,0.619445,0.0,0
1,82,Calione Fuentes,12:57:16.43,57436.43,-17.448955,-28.076782,0.619445,0.0,0
2,82,Calione Fuentes,12:57:16.44,57436.44,-17.448955,-28.076782,0.619445,0.0,0
3,82,Calione Fuentes,12:57:16.45,57436.45,-17.448955,-28.076782,0.619445,0.0,0
4,82,Calione Fuentes,12:57:16.46,57436.46,-19.630074,-31.586380,0.405556,0.0,0

Cargando datos... Rentistas 26-7-2024.csv
Table rentistas has new line in column names: False
Table rentistas already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,71,Echeverría Aznarez,08:57:04.50,0.099999,-34.776965,-56.165413,1.940002,3.900003,0
1,71,Echeverría Aznarez,08:57:04.60,0.199999,-34.776966,-56.165413,1.420001,5.200004,0
2,71,Echeverría Aznarez,08:57:04.70,0.299998,-34.776965,-56.165414,1.210001,2.100002,0
3,71,Echeverría Aznarez,08:57:04.80,0.399997,-34.776964,-56.165414,1.090001,1.200001,0
4,71,Echeverría Aznarez,08:57:04.80,0.399997,-34.776964,-56.165414,1.090001,0.000000,0

Cargando datos... Juventud 19-7-2024.csv
Table juventud has new line in column names: False
Table juventud already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,71,Echeverría Aznarez,09:00:55.70,0.099999,-34.795335,-56.147942,0.0,0.0,0
1,71,Echeverría Aznarez,09:00:55.80,0.199999,-34.795335,-56.147943,0.0,0.0,0
2,71,Echeverría Aznarez,09:00:55.90,0.299998,-34.795335,-56.147943,0.0,0.0,0
3,71,Echeverría Aznarez,09:00:56.00,0.399998,-34.795335,-56.147943,0.0,0.0,0
4,71,Echeverría Aznarez,09:00:56.10,0.500005,-34.795335,-56.147943,0.0,0.0,0

Cargando datos... Torque 10-5-2024.csv
Table torque has new line in column names: False
Table torque already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,08:58:56.30,0.099999,-34.786833,-56.006922,0.000000,0.0,0
1,68,Del Pino Esquivo,08:58:56.40,0.199999,-34.786833,-56.006922,0.000000,0.0,0
2,68,Del Pino Esquivo,08:58:56.50,0.299998,-34.786832,-56.006921,0.000000,0.0,0
3,68,Del Pino Esquivo,08:58:56.60,0.399997,-34.786831,-56.006923,0.000000,0.0,0
4,68,Del Pino Esquivo,08:58:56.70,0.499997,-34.786831,-56.006923,1.130001,0.0,0

Cargando datos... Liverpool 23-3-2024.csv
Table liverpool has new line in column names: False
Table liverpool already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,08:02:32.90,0.099999,-34.795008,-56.147398,2.160002,2.400002,0
1,68,Del Pino Esquivo,08:02:33.00,0.199998,-34.795007,-56.147398,2.140002,0.200000,0
2,68,Del Pino Esquivo,08:02:33.10,0.299998,-34.795007,-56.147397,2.180002,0.400000,0
3,68,Del Pino Esquivo,08:02:33.20,0.399997,-34.795008,-56.147397,2.270002,0.900001,0
4,68,Del Pino Esquivo,08:02:33.30,0.499997,-34.795010,-56.147397,2.700002,4.300003,0

Cargando datos... Racing 31-5-2024.csv
Table racing has new line in column names: False
Table racing already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,08:49:32.60,0.099999,-34.855593,-56.308497,0.0,0.0,0
1,68,Del Pino Esquivo,08:49:32.70,0.199999,-34.855592,-56.308496,0.0,0.0,0
2,68,Del Pino Esquivo,08:49:32.80,0.299998,-34.855592,-56.308496,0.0,0.0,0
3,68,Del Pino Esquivo,08:49:32.90,0.399998,-34.855592,-56.308495,0.0,0.0,0
4,68,Del Pino Esquivo,08:49:33.00,0.500005,-34.855592,-56.308496,0.0,0.0,0

Cargando datos... Danubio 26-3-2024.csv
Table danubio has new line in column names: False
Table danubio already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,09:00:07.80,0.099999,-34.795340,-56.147774,4.150003,2.500002,0
1,68,Del Pino Esquivo,09:00:07.90,0.199998,-34.795340,-56.147774,3.250003,9.000008,0
2,68,Del Pino Esquivo,09:00:08.00,0.299998,-34.795340,-56.147774,3.730003,4.800004,0
3,68,Del Pino Esquivo,09:00:08.10,0.399997,-34.795345,-56.147778,3.590003,1.400001,0
4,68,Del Pino Esquivo,09:00:08.20,0.499997,-34.795345,-56.147785,3.950003,3.600003,0

Cargando datos... Plaza 13-4-2024.csv
Table plaza has new line in column names: False
Table plaza already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,10:03:16.50,0.099999,-34.795130,-56.148069,0.0,0.0,0
1,68,Del Pino Esquivo,10:03:16.60,0.199999,-34.795129,-56.148070,0.0,0.0,0
2,68,Del Pino Esquivo,10:03:16.70,0.299998,-34.795128,-56.148071,0.0,0.0,0
3,68,Del Pino Esquivo,10:03:16.80,0.399997,-34.795128,-56.148072,0.0,0.0,0
4,68,Del Pino Esquivo,10:03:16.90,0.500005,-34.795129,-56.148072,0.0,0.0,0

Cargando datos... BellaVista 2-7-2024.csv
Table bellavista has new line in column names: False
Table bellavista already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,08:55:38.70,0.099999,-34.863766,-56.311960,1.600001,0.0,0
1,68,Del Pino Esquivo,08:55:38.80,0.199998,-34.863768,-56.311958,1.800001,0.0,0
2,68,Del Pino Esquivo,08:55:38.90,0.300007,-34.863769,-56.311958,1.230001,0.0,0
3,68,Del Pino Esquivo,08:55:39.00,0.400006,-34.863769,-56.311959,0.000000,0.0,0
4,68,Del Pino Esquivo,08:55:39.10,0.500005,-34.863769,-56.311960,0.000000,0.0,0

Cargando datos... Paysandu 19-7-2024.csv
Table paysandu has new line in column names: False
Table paysandu already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,71,Echeverría Aznarez,09:00:55.70,0.099999,-34.795335,-56.147942,0.0,0.0,0
1,71,Echeverría Aznarez,09:00:55.80,0.199999,-34.795335,-56.147943,0.0,0.0,0
2,71,Echeverría Aznarez,09:00:55.90,0.299998,-34.795335,-56.147943,0.0,0.0,0
3,71,Echeverría Aznarez,09:00:56.00,0.399998,-34.795335,-56.147943,0.0,0.0,0
4,71,Echeverría Aznarez,09:00:56.10,0.500005,-34.795335,-56.147943,0.0,0.0,0

Cargando datos... Miramar 8-6-2024.csv
Table miramar has new line in column names: False
Table miramar already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,09:01:08.10,0.099999,-34.795324,-56.147783,3.850003,0.0,0
1,68,Del Pino Esquivo,09:01:08.20,0.199998,-34.795323,-56.147790,4.650004,0.0,0
2,68,Del Pino Esquivo,09:01:08.30,0.300007,-34.795323,-56.147794,4.580004,0.0,0
3,68,Del Pino Esquivo,09:01:08.40,0.400006,-34.795323,-56.147797,4.380004,0.0,0
4,68,Del Pino Esquivo,09:01:08.50,0.500005,-34.795323,-56.147800,4.030003,0.0,0

Cargando datos... Fenix 16-8-2024.csv
Table fenix has new line in column names: False
Table fenix already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,15:59:18.50,0.099999,-34.897800,-56.153678,2.140002,4.600004,0
1,68,Del Pino Esquivo,15:59:18.60,0.199999,-34.897800,-56.153678,2.580002,4.400004,0
2,68,Del Pino Esquivo,15:59:18.70,0.299998,-34.897799,-56.153679,2.250002,3.300003,0
3,68,Del Pino Esquivo,15:59:18.80,0.399998,-34.897800,-56.153679,2.520002,2.700002,0
4,68,Del Pino Esquivo,15:59:18.90,0.499997,-34.897800,-56.153678,2.580002,0.600000,0

Cargando datos... Wanderers 20-4-2024.csv
Table wanderers has new line in column names: False
Table wanderers already exists

,player_id,player_display_name,time,elapsed_time,lat,lon,speed,instantaneous_acceleration,heart_rate
0,68,Del Pino Esquivo,1866,57:38.0,0.019998,0.719445,0.638889,0,-34.853875
1,68,Del Pino Esquivo,1866,57:38.0,0.029999,0.719445,0.638889,0,-34.853875
2,68,Del Pino Esquivo,1866,57:38.0,0.039999,0.719445,0.638889,0,-34.853875
3,68,Del Pino Esquivo,1866,57:38.0,0.049998,0.719445,0.638889,0,-34.853875
4,68,Del Pino Esquivo,1866,57:38.1,0.059998,0.719445,0.638889,0,-34.853875

In [13]:
# Cargando datos... Rentistas 26-7-2024.csv
# ---------------------------------------------------------------------------
# UnicodeDecodeError                        Traceback (most recent call last)
# Cell In[7], line 4
#       2 for file_name in os.listdir('work/cargar_datos_base/partidos'):
#       3     if file_name.endswith('.csv'):
# ----> 4         process_rival_data(file_name, engine)

# Cell In[6], line 31
#      24 column_names = [
#      25     "Player Id", "Player Display Name", "Time", "Elapsed Time (s)",
#      26     "Lat", "Lon", "Speed km/h", "Instantaneous Acceleration Impulse", "Heart Rate (bpm)", ""
#      27 ]
#      29 file = 'work/cargar_datos_base/partidos/' + file_name
# ---> 31 datos_csv = pd.read_csv(file, delimiter=',', skiprows=1, names=column_names)
#      32 datos_csv = datos_csv.iloc[:, :-1]  # remove the last column, because the csv file has an extra comma at the end
#      33 datos_csv = rename_columns(datos_csv)  # rename the columns to something more db friendly

# File /opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py:1026, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
#    1013 kwds_defaults = _refine_defaults_read(
#    1014     dialect,
#    1015     delimiter,
#    (...)
#    1022     dtype_backend=dtype_backend,
#    1023 )
#    1024 kwds.update(kwds_defaults)
# ...
# File parsers.pyx:891, in pandas._libs.parsers.TextReader._check_tokenize_status()

# File parsers.pyx:2053, in pandas._libs.parsers.raise_parser_error()

# UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 144: invalid continuation byte


# The error is because the file is not in utf-8 encoding. Let's replace the line that causes the error with the following code:
def get_rival_name(file_name):
        """
        Get the name of the rival from the file name
        'Albion 25-5-2024.csv'     -> albion
        """
        return file_name.split(' ')[0].lower()

def rename_columns(df):
    """
    Rename the columns of the dataframe
    rename columns, because right now those look like this
    "Player Id", " Player Display Name", " Time", " Elapsed Time (s)", " Lat", " Lon", "  Speed km/h", " Instantaneous Acceleration Impulse", " Heart Rate (bpm)"
    and we want them to look like this
    player_id, player_display_name, "time", elapsed_time, lat, lon, speed, instantaneous_acceleration, heart_rate
    """
    df.columns = ['player_id', 'player_display_name', 'time', 'elapsed_time', 'lat', 'lon', 'speed', 'instantaneous_acceleration', 'heart_rate']
    return df

def process_rival_data(file_name, engine):
    

    print(f"Cargando datos... {file_name}")

    current_rival = get_rival_name(file_name)

    column_names = [
        "Player Id", "Player Display Name", "Time", "Elapsed Time (s)",
        "Lat", "Lon", "Speed km/h", "Instantaneous Acceleration Impulse", "Heart Rate (bpm)", ""
    ]

    file = 'work/cargar_datos_base/partidos/' + file_name

    datos_csv = pd.read_csv(file, delimiter=',', skiprows=1, names=column_names, encoding='latin1')
    datos_csv = datos_csv.iloc[:, :-1]  # remove the last column, because the csv file has an extra comma at the end
    datos_csv = rename_columns(datos_csv)  # rename the columns to something more db friendly

    with engine.connect() as conn, conn.begin():
        from sqlalchemy import text
        query = text(f"SELECT * FROM information_schema.tables WHERE table_name = '{current_rival}'")
        table_exists = conn.execute(query).fetchone()
        if table_exists:
            print(f"Table {current_rival} already exists")
        else:
            print(f"Table {current_rival} does not exist")
            datos_csv.to_sql(current_rival, conn, if_exists='replace', index=False)

    try:
        query = f"SELECT * FROM {current_rival} LIMIT 5"
        df = pd.read_sql(query, engine)
        
        # check the name of any of the columns in df contains \n
        for col in df.columns:
            if '\n' in col:
                print(f"Column name {col} contains a newline character")
        
        
        # display(df)
    except Exception as e:
        print(e)
        print("Error al leer la tabla")

In [14]:
# # now run the function for all the files in the directory
# for file_name in os.listdir('work/cargar_datos_base/partidos'):
#     if file_name.endswith('.csv'):
#         process_rival_data(file_name, engine)

In [15]:
# pd.options.mode.chained_assignment = None

# size_tiempo = 1
# chunk = 1

# # if not datos_jugadores:
# #     datos_jugadores = {}

# def calcular_metricas_intervalo(datos_csv):
#     # print("[detectar_peores_escenarios]", datos_csv)

#     jugadores = datos_csv['player_id'].unique()
#     ultima_ventana_anterior = 0
#     datos_jugadores = {}
    
#     for k, jugador in enumerate(jugadores):
#         if jugador not in datos_jugadores:
#             print("agregando nueva entrada a datos_jugadores:: ", jugador)
#             datos_jugadores[jugador] = datos_csv[datos_csv['player_id'] == jugador]
#         else:
#             print("datos_jugadores cargados hasta el momento: ", len(datos_jugadores))
#         print("jugador:", jugador) # datos_jugadores[jugador].loc[0, 'player_display_name'])

        
#         ultima_ventana_jugador = len(datos_jugadores[jugador]) - chunk
#         # print("datos_jugador", datos_jugador)
#         print("ultima_ventana_jugador", ultima_ventana_jugador)
        
#         # for i in range(ultima_ventana_anterior, ultima_ventana_anterior+ultima_ventana_jugador, chunk):
#         for i in range(0, ultima_ventana_jugador, chunk):
#             j = i + chunk
#             if (j%(10000/(k+1))==0):
#                 print("Jugador:", jugador, " -- iteraciones realizadas: ", j)
#                 print("datos_jugadores[jugador]", i, datos_jugadores[jugador].iloc[i])
#                 print("datos_jugadores[jugador]", i+1, datos_jugadores[jugador].iloc[i+1])
          
#             if i == 0:
#                 try:
#                     print("try, i:", i)
#                     # datos_jugadores[jugador].loc[i][9]
#                     distancias_ya_calculadas = datos_jugadores[jugador].iloc[:, 9]
#                     print("distancias_ya_calculadas", distancias_ya_calculadas)
#                     if not distancias_ya_calculadas.isna().any().any():
#                         print("todas las distancias_ya_calculadas, porque no hay NaNs me voy al siguiente")
#                         break
#                     else:
#                         print("distancias_ya_calculadas", distancias_ya_calculadas)
#                         i = distancias_ya_calculadas.isna().idxmax()
#                         print("i despues", i)

#                 except IndexError:
#                     print ("IndexError, asi queue es primera iteracion")
            
#             datos_jugadores[jugador] = datos_jugadores[jugador].reset_index(drop=True)
#             if (j%(10000/(k+1))==0):
#                 print("datos_jugadores[jugador]", datos_jugadores[jugador])

#             intervalo = datos_jugadores[jugador].iloc[i:j+chunk]

#             distancia_total = calcular_distancia(intervalo)
#             hsr_total = calcular_hsr(intervalo)
#             sprint_total = calcular_sprints(intervalo)
#             aceleraciones = contar_aceleraciones(intervalo)
#             desaceleraciones = contar_desaceleraciones(intervalo)
#             hml_distance = calcular_hml_distance(intervalo)
#             amp = calcular_amp(intervalo)

#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'distancia_total_calc'] = distancia_total
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'hsr_total_calc'] = hsr_total
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'sprint_total_calc'] = sprint_total
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'aceleraciones_calc'] = aceleraciones
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'desaceleraciones_calc'] = desaceleraciones
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'hml_distance_calc'] = hml_distance
#             datos_jugadores[jugador].loc[i-ultima_ventana_anterior, 'amp_calc'] = amp
                
#         ultima_ventana_anterior = ultima_ventana_jugador
#         print(datos_jugadores[jugador].describe())
#         datos_jugadores[jugador]['distancia_total_calc'].sum()

In [ ]:

barrera_hsr = 19.8 # (5.5 * 3.6)
barrera_hmld = 2
barrera_sprint = 17
size_tiempo = 1
chunk = 10
datos_jugadores = {}


def haversine_distance(lat1, lon1, lat2, lon2):
    # print("[haversine_distance]", lat1, lon1, lat2, lon2)
    # Calcula la distancia entre dos puntos en la Tierra utilizando la fórmula de Haversine
    R = 6371e3  # Radio de la Tierra en metros
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)

    # print("R", R)
    # print("phi1", phi1)
    # print("phi2", phi2)
    
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    # print("delta_phi", delta_phi)
    # print("delta_lambda", delta_lambda)
    
    
    a = np.sin(delta_phi/2) * np.sin(delta_phi/2) + \
        np.cos(phi1) * np.cos(phi2) * \
        np.sin(delta_lambda/2) * np.sin(delta_lambda/2)

    # print("a", a)

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    # print("c", c)

    distancia = R * c
    return distancia
  
def calcular_coeficientes(intervalo):
    # print("[calcular_distancia] len(intervalo)", len(intervalo))
    # print("[calcular_distancia] intervalo", intervalo)
    # Calcula la distancia total en el intervalo
    # Usar la fórmula de la distancia entre coordenadas (lat, lon)
    distancia_total = 0.0
    lat1, lon1, speed1 = intervalo.iloc[0][['lat', 'lon', 'speed']]
    lat2, lon2, speed2 = intervalo.iloc[-1][['lat', 'lon', 'speed']]
    # print("[calcular_distancia]", lat1, lon1, lat2, lon2)
    
    # distancia
    distancia_total += haversine_distance(lat1, lon1, lat2, lon2)

    # aceleracion
    aceleracion = 2 * (distancia_total - speed1) # se tiene que multiplicar y divir por uno, lo cual es lo mismo
    
    speed_mean = intervalo['speed'].mean()

    sprint_total = 0
    if speed_mean >= barrera_sprint:
        sprint_total =  speed_mean


    aceleracion = aceleracion if aceleracion >= barrera_hmld else 0
    desaceleracion = aceleracion if aceleracion<= -barrera_hmld else 0
    
    return distancia_total, sprint_total, speed_mean, aceleracion, desaceleracion
    
def calcular_metricas_intervalo(datos_csv):
    print("[detectar_peores_escenarios]", datos_csv)

    jugadores = datos_csv['player_id'].unique()
    ultima_ventana_anterior = 0
    datos_jugadores = {}
    
    print("jugadores", jugadores)
    
    for k, jugador in enumerate(jugadores):
        if jugador not in datos_jugadores:
            print("agregando nueva entrada a datos_jugadores:: ", jugador)
            datos_jugadores[jugador] = datos_csv[datos_csv['player_id'] == jugador]
        else:
            print("datos_jugadores cargados hasta el momento: ", len(datos_jugadores))
        print("jugador:", jugador) # datos_jugadores[jugador].loc[0, 'player_display_name'])

        
        ultima_ventana_jugador = len(datos_jugadores[jugador]) - chunk
        print("datos_jugador", datos_jugadores[jugador])
        print("ultima_ventana_jugador", ultima_ventana_jugador)
        
        for i in range(ultima_ventana_anterior, ultima_ventana_anterior+ultima_ventana_jugador, chunk):
            for i in range(0, ultima_ventana_jugador, chunk):
                j = i + chunk
                if (j%(10000/(k+1))==0):
                    print("Jugador:", jugador, " -- iteraciones realizadas: ", j)
                    # print("datos_jugadores[jugador] i", i, datos_jugadores[jugador].iloc[i])
                    # print("datos_jugadores[jugador] i + 1", i+1, datos_jugadores[jugador].iloc[i+1])
                    # print("datos_jugadores[jugador] j", j, datos_jugadores[jugador].iloc[j])
                # print("i", i)
                # print("J", j)
                
                

                # print("datos_jugadores[jugador].loc[i]", datos_jugadores[jugador].loc[i])
                # print("loc[0]", )
                # print("type", type(datos_jugadores[jugador].loc[i]))


                # print("111", datos_jugadores[jugador])
                # print("222", type(datos_jugadores[jugador]))
                if i == 0:
                    try:
                        print("try, i:", i)
                        # datos_jugadores[jugador].loc[i][9]
                        distancias_ya_calculadas = datos_jugadores[jugador].iloc[:, 9]
                        print("distancias_ya_calculadas", distancias_ya_calculadas)
                        if not distancias_ya_calculadas.isna().any().any():
                            print("todas las distancias_ya_calculadas, porque no hay NaNs me voy al siguiente")
                            break
                        else:
                            print("distancias_ya_calculadas", distancias_ya_calculadas)
                            i = distancias_ya_calculadas.isna().idxmax()
                            print("i despues", i)

                    except IndexError:
                        print ("IndexError, asi queue es primera iteracion")
                # print("calculando")
                # print("datos_jugadores[jugador]", datos_jugadores[jugador])
                datos_jugadores[jugador] = datos_jugadores[jugador].reset_index(drop=True)
                if (j%(10000/(k+1))==0):
                    print("datos_jugadores[jugador]", datos_jugadores[jugador])

                intervalo = datos_jugadores[jugador].iloc[i:j]

                # distancia_total, hsr_total = calcular_distancia(intervalo)
                # sprint_total = calcular_sprints(intervalo)
                # aceleraciones = contar_aceleraciones(intervalo)
                # desaceleraciones = contar_desaceleraciones(intervalo)
                # hml_distance = calcular_hml_distance(intervalo)
                # amp = calcular_amp(intervalo)

                # distancia_total, hsr_total, sprint_total, speed_mean, aceleracion, desaceleracion, hmld_total = calcular_coeficientes(intervalo)
                distancia_total, sprint_total, speed_mean, aceleracion, desaceleracion= calcular_coeficientes(intervalo)

                if speed_mean > 10 and (aceleracion or desaceleracion):
                    print(f"STATS:::: distancia_total: {distancia_total}, sprint_total: {sprint_total}, speed_mean: {speed_mean}, aceleracion: {aceleracion}, desaceleracion: {desaceleracion}")
                    print(intervalo)
                # print("antes\n", datos_jugadores[jugador].loc[i])

                # persistir estos datos en el df
                datos_jugadores[jugador].loc[i, 'distancia_total_calc'] = distancia_total
                datos_jugadores[jugador].loc[i, 'sprint_total'] = sprint_total
                datos_jugadores[jugador].loc[i, 'aceleraciones_calc'] = aceleracion
                datos_jugadores[jugador].loc[i, 'desaceleraciones_calc'] = desaceleracion
                datos_jugadores[jugador].loc[i, 'speed_mean_calc'] = speed_mean
                # datos_jugadores[jugador].loc[i, 'amp_calc'] = amp
                    
                # print("después\n", datos_jugadores[jugador].loc[i])
            ultima_ventana_anterior = ultima_ventana_jugador
        print("DESCRIBINGGGG", datos_jugadores[jugador].describe())
        datos_jugadores[jugador]['distancia_total_calc'].sum()
    return datos_jugadores

In [ ]:
import psycopg2
from sqlalchemy import text

def process_and_store_data(engine, table_name):
  print(f"Processing and storing data for table '{table_name}'...")
  

  # # Replace the placeholder values with your actual database credentials
  host = "localhost"
  database = "nacional"
  user = "nacional"
  password = "nacional"

  # Connect to the PostgreSQL database
  conn = psycopg2.connect(
    host=host,
    database=database,
    user=user,
    password=password
  )

  data_type_map = {
    "int64": "INTEGER",
    "float64": "DOUBLE PRECISION",
    "object": "VARCHAR",  # Adjust as needed for your database
  }

  cur = conn.cursor()
  # # Drop the table if it exists
  try:
    cur.execute(f"DROP TABLE IF EXISTS {table_name}_processed")
    print(f"Table '{table_name}_processed' dropped successfully.")
  except psycopg2.ProgrammingError as e:
    print(f"Error dropping table '{table_name}': {e}")
    
  query = text(f"SELECT * FROM {table_name}")
  print(f"query: {query}")
  datos_csv = pd.read_sql_query(query, engine)

  print(f"datos_csv: {len(datos_csv)}")
  datos_jugadores = calcular_metricas_intervalo(datos_csv)
  print(f"datos_jugadores: {len(datos_jugadores)}")
  # return None
  

  for n in datos_jugadores.keys():
    df = datos_jugadores[n]
    print(type(df))
    # Get the DataFrame's column names and data types
    column_names = df.columns.tolist()
    column_types = []
    for col in df:
      print(f"Processing column: {col}")
      # Get the pandas data type
      pd_type = df[col].dtype.name
      print(f"Pandas data type for column {col}: {pd_type}")
      # Find the corresponding PostgreSQL data type
      data_type = data_type_map.get(pd_type, None)
      if data_type is None:
        # Handle unsupported data types (optional: raise an error or use a default)
        raise ValueError(f"Unsupported data type for column {col}: {df[col].dtype}")
      print(f"Data type for column {col}: {data_type}")
      column_types.append(data_type)

    # Create the SQL statement to create the table
    create_table_sql = f"""
    CREATE TABLE {table_name}_processed (
      {', '.join(f"{col_name} {col_type}" for col_name, col_type in zip(column_names, column_types))}
    )
    """

    # Execute the SQL statement to create the table
    cur.execute(create_table_sql)

    # Prepare the SQL statement for inserting values
    insert_values_sql = f"""
    INSERT INTO {table_name}_processed ({', '.join(column_names)})
    VALUES ({', '.join(['%s'] * len(column_names))})
    """

    # Iterate over each row in the DataFrame and insert the values
    for _, row in df.iterrows():
      print("inserting row", row)
      values = tuple(row)
      cur.execute(insert_values_sql, values)

    # Commit the changes to the database
    conn.commit()
  
  
  # cur = conn.cursor()
  # # Drop the table if it exists
  # try:
  #     cur.execute(f"DROP TABLE IF EXISTS {table_name}")
  #     print(f"Table '{table_name}' dropped successfully.")
  # except psycopg2.ProgrammingError as e:
  #     print(f"Error dropping table '{table_name}': {e}")


  # # Create the SQL statement to create the table
  # create_table_sql = f"""
  # CREATE TABLE {table_name} (
  #     {', '.join(f"{col_name} {col_type}" for col_name, col_type in zip(column_names, column_types))}
  # )
  # """

  # # Execute the SQL statement to create the table
  # cur.execute(create_table_sql)
  # # Close the cursor and connection
  # cur.close()

  # # Create a cursor object to execute SQL statements
  # cur = conn.cursor()
  # for n in datos_jugadores.keys():
  #     df = datos_jugadores[n]
  #     print(type(df))
  #     # Get the DataFrame's column names and data types
  #     # column_names = f"{rival}_processed"
  #     column_names = df.columns.tolist()
  #     column_types = []
  #     for col in df:
  #         print(f"Processing column: {col}")
  #         # Get the pandas data type
  #         pd_type = df[col].dtype.name
  #         print(f"Pandas data type for column {col}: {pd_type}")
  #         # Find the corresponding PostgreSQL data type
  #         data_type = data_type_map.get(pd_type, None)
  #         if data_type is None:
  #             # Handle unsupported data types (optional: raise an error or use a default)
  #             raise ValueError(f"Unsupported data type for column {col}: {df[col].dtype}")
  #         print(f"Data type for column {col}: {data_type}")
  #         column_types.append(data_type)

      
  #     # Prepare the SQL statement for inserting values
  #     insert_values_sql = f"""
  #     INSERT INTO {table_name} ({', '.join(column_names)})
  #     VALUES ({', '.join(['%s'] * len(column_names))})
  #     """


  #     # Iterate over each row in the DataFrame and insert the values
  #     for _, row in df.iterrows():
  #         values = tuple(row)
  #         cur.execute(insert_values_sql, values)
      
  #     # Commit the changes to the database
  #     conn.commit()

  # Close the cursor and connection
  cur.close()
  conn.close()

In [ ]:
# # run it for wanderers

filename = 'Fenix 16-8-2024.csv'
current_rival = get_rival_name(filename)
print(current_rival)
datos_jugadores = process_and_store_data(engine, current_rival)

In [ ]:
print("hola")

In [ ]:
# # select * from wanderers_processed limit 5;

# df = pd.read_sql_query("select * from wanderers_processed limit 5;", engine)
# display(df)

In [ ]:
# # now call process_and_store_data and store the data for all the matches
 
# for file_name in os.listdir('work/cargar_datos_base/partidos'):
#     print(f"running: ", file_name)
#     if file_name.endswith('.csv'):
#         current_rival = get_rival_name(file_name)
#         datos_jugadores = process_and_store_data(engine, current_rival)